[pytest]
python_files = test_*.py
norecursedirs = .git .venv build dist
python_classes = Test*
python_functions = test_*
markers =
    qt: marks tests as involving Qt (GUI)
    slow: marks tests as slow (deselect with '-m "not slow"')
    engine: marks tests requiring a chess engine
addopts = -v --ignore=test_detail_80.txt
