; Script generated by Antigravity for Opening Fenix
; Inno Setup 6.0+ Script

#ifndef AppBuildType
#define AppBuildType "Private"
#endif

#define MyAppName "Opening Fenix"
#ifndef MyAppVersion
#define MyAppVersion "0.9.1"
#endif
#define MyAppPublisher "Opening Fenix Team"
#define MyAppURL "https://github.com"
#define MyAppExeName "Opening Fenix.exe"
#define MyOutputBaseFilename "OpeningFenix_Setup_v" + MyAppVersion + "_" + AppBuildType

[Setup]
AppId={{D37E84B1-29A4-4E67-8F12-78A3311E6F01}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=
OutputDir=..\Output
OutputBaseFilename={#MyOutputBaseFilename}
SetupIconFile=..\assets\Logo\favicon.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "en"; MessagesFile: "compiler:Default.isl"
Name: "de"; MessagesFile: "compiler:Languages\German.isl"

[CustomMessages]
de.LichessTitle=Lichess API Schlüssel (Optional)
de.LichessSubTitle=Verbinde Lichess, um Meisterschafts-Datenbanken & Cloud-Analysen zu nutzen.
de.LichessDesc=Mit einem Lichess API Schlüssel kannst du Meister-Partien und Stellungsstatistiken direkt in Opening Fenix abrufen.
de.LichessPrompt=Lichess API Schlüssel (Token):
de.LichessLinkText=🔗 API-Schlüssel auf Lichess.org erstellen (im Browser öffnen)
de.LichessSkipHint=Hinweis: Du kannst dieses Feld leer lassen (Überspringen) und den Schlüssel später in den Einstellungen eintragen.
en.LichessTitle=Lichess API Key (Optional)
en.LichessSubTitle=Connect Lichess to access master databases & cloud evaluations.
en.LichessDesc=A Lichess API key allows Opening Fenix to fetch master games and position statistics.
en.LichessPrompt=Lichess API Key (Token):
en.LichessLinkText=🔗 Create API Key on Lichess.org (Opens in browser)
en.LichessSkipHint=Note: You can leave this blank (Skip) and enter your key later in Settings.

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "..\dist\Opening Fenix\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\{#MyAppExeName}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
var
  LichessPage: TWizardPage;
  LichessEdit: TNewEdit;
  LichessLinkLabel: TNewStaticText;

procedure OpenLichessUrl(Sender: TObject);
var
  ErrorCode: Integer;
begin
  ShellExec('open', 'https://lichess.org/account/oauth/token', '', '', SW_SHOWNORMAL, ewNoWait, ErrorCode);
end;

procedure InitializeWizard;
var
  DescLabel: TNewStaticText;
  PromptLabel: TNewStaticText;
  SkipLabel: TNewStaticText;
begin
  { Create custom page after destination folder selection page }
  LichessPage := CreateCustomPage(wpSelectDir, ExpandConstant('{cm:LichessTitle}'), ExpandConstant('{cm:LichessSubTitle}'));

  DescLabel := TNewStaticText.Create(LichessPage);
  DescLabel.Parent := LichessPage.Surface;
  DescLabel.Caption := ExpandConstant('{cm:LichessDesc}');
  DescLabel.Left := 0;
  DescLabel.Top := 0;
  DescLabel.Width := LichessPage.SurfaceWidth;
  DescLabel.WordWrap := True;

  LichessLinkLabel := TNewStaticText.Create(LichessPage);
  LichessLinkLabel.Parent := LichessPage.Surface;
  LichessLinkLabel.Caption := ExpandConstant('{cm:LichessLinkText}');
  LichessLinkLabel.Left := 0;
  LichessLinkLabel.Top := DescLabel.Top + DescLabel.Height + 15;
  LichessLinkLabel.Font.Color := clBlue;
  LichessLinkLabel.Font.Style := [fsUnderline];
  LichessLinkLabel.Cursor := crHand;
  LichessLinkLabel.OnClick := @OpenLichessUrl;

  PromptLabel := TNewStaticText.Create(LichessPage);
  PromptLabel.Parent := LichessPage.Surface;
  PromptLabel.Caption := ExpandConstant('{cm:LichessPrompt}');
  PromptLabel.Left := 0;
  PromptLabel.Top := LichessLinkLabel.Top + 35;

  LichessEdit := TNewEdit.Create(LichessPage);
  LichessEdit.Parent := LichessPage.Surface;
  LichessEdit.Left := 0;
  LichessEdit.Top := PromptLabel.Top + 20;
  LichessEdit.Width := LichessPage.SurfaceWidth;

  SkipLabel := TNewStaticText.Create(LichessPage);
  SkipLabel.Parent := LichessPage.Surface;
  SkipLabel.Caption := ExpandConstant('{cm:LichessSkipHint}');
  SkipLabel.Left := 0;
  SkipLabel.Top := LichessEdit.Top + 35;
  SkipLabel.Width := LichessPage.SurfaceWidth;
  SkipLabel.WordWrap := True;
  SkipLabel.Font.Style := [fsItalic];
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ConfigPath: String;
  LichessKey: String;
  LangCode: String;
  EnginePath: String;
  JsonContent: String;
  EscapedEnginePath: String;
  IsPublicStr: String;
begin
  if CurStep = ssPostInstall then
  begin
    LichessKey := Trim(LichessEdit.Text);
    LangCode := ExpandConstant('{language}');
    if LangCode <> 'de' then
      LangCode := 'en';

    #if AppBuildType == "Public"
    IsPublicStr := 'true';
    #else
    IsPublicStr := 'false';
    #endif

    EnginePath := ExpandConstant('{app}') + '\engines\stockfish-windows-x86-64-avx2.exe';
    EscapedEnginePath := EnginePath;
    StringChangeEx(EscapedEnginePath, '\', '\\', True);

    ConfigPath := ExpandConstant('{app}') + '\config.json';

    JsonContent := '{' + #13#10 +
      '    "engine_path": "' + EscapedEnginePath + '",' + #13#10 +
      '    "lichess_token": "' + LichessKey + '",' + #13#10 +
      '    "ui_language": "' + LangCode + '",' + #13#10 +
      '    "is_public": ' + IsPublicStr + ',' + #13#10 +
      '    "master_volume": 30,' + #13#10 +
      '    "engine_threads": "4",' + #13#10 +
      '    "engine_hash": "256",' + #13#10 +
      '    "engine_depth": "20",' + #13#10 +
      '    "engine_multipv": "3"' + #13#10 +
      '}';

    SaveStringToFile(ConfigPath, JsonContent, False);
  end;
end;
