; Script generated by Antigravity for Opening Fenix
; Inno Setup 6.0+ Script

#ifndef AppBuildType
#define AppBuildType "Private"
#endif

#define MyAppName "Opening Fenix"
#ifndef MyAppVersion
#define MyAppVersion "0.9.3"
#endif
#define MyAppPublisher "Opening Fenix Team"
#define MyAppURL "https://github.com"
#define MyAppExeName "Opening Fenix.exe"
#define MyOutputBaseFilename "OpeningFenix_Setup_v" + MyAppVersion + "_" + AppBuildType

[Setup]
AppId={{D37E84B1-29A4-4E67-8F12-78A3311E6F01}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=
OutputDir=..\Output
OutputBaseFilename={#MyOutputBaseFilename}
SetupIconFile=..\assets\Logo\favicon.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\{#MyAppExeName}
UsePreviousLanguage=yes
ShowLanguageDialog=auto
CloseApplications=yes

[Languages]
Name: "en"; MessagesFile: "compiler:Default.isl"
Name: "de"; MessagesFile: "compiler:Languages\German.isl"

[CustomMessages]
de.LichessTitle=Lichess API Schlüssel (Optional)
de.LichessSubTitle=Verbinde Lichess, um Meisterschafts-Datenbanken & Cloud-Analysen zu nutzen.
de.LichessDesc=Mit einem Lichess API Schlüssel kannst du Meister-Partien und Stellungsstatistiken direkt in Opening Fenix abrufen.
de.LichessPrompt=Lichess API Schlüssel (Token):
de.LichessLinkText=🔗 API-Schlüssel auf Lichess.org erstellen (im Browser öffnen)
de.LichessSkipHint=Hinweis: Du kannst dieses Feld leer lassen (Überspringen) und den Schlüssel später in den Einstellungen eintragen.
en.LichessTitle=Lichess API Key (Optional)
en.LichessSubTitle=Connect Lichess to access master databases & cloud evaluations.
en.LichessDesc=A Lichess API key allows Opening Fenix to fetch master games and position statistics.
en.LichessPrompt=Lichess API Key (Token):
en.LichessLinkText=🔗 Create API Key on Lichess.org (Opens in browser)
en.LichessSkipHint=Note: You can leave this blank (Skip) and enter your key later in Settings.

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "..\dist\Opening Fenix\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\{#MyAppExeName}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall

[Code]
var
  LichessPage: TWizardPage;
  LichessEdit: TNewEdit;
  LichessLinkLabel: TNewStaticText;
  ExistingLichessToken: String;
  ExistingLanguage: String;
  ExistingIsPublicSet: Boolean;
  ExistingIsPublic: Boolean;
  IsUpgradeMode: Boolean;

function ExtractJsonValue(const Json, Key: String): String;
var
  P, P2, P3: Integer;
  SearchKey: String;
begin
  Result := '';
  SearchKey := '"' + Key + '"';
  P := Pos(SearchKey, Json);
  if P > 0 then
  begin
    P := P + Length(SearchKey);
    P2 := Pos(':', Copy(Json, P, Length(Json) - P + 1));
    if P2 > 0 then
    begin
      P := P + P2;
      P2 := Pos('"', Copy(Json, P, Length(Json) - P + 1));
      if P2 > 0 then
      begin
        P := P + P2;
        P3 := Pos('"', Copy(Json, P, Length(Json) - P + 1));
        if P3 > 0 then
        begin
          Result := Copy(Json, P, P3 - 1);
        end;
      end;
    end;
  end;
end;

function ExtractJsonBool(const Json, Key: String; DefaultVal: Boolean): Boolean;
var
  P, P2, PEnd: Integer;
  SearchKey, ValStr: String;
begin
  Result := DefaultVal;
  SearchKey := '"' + Key + '"';
  P := Pos(SearchKey, Json);
  if P > 0 then
  begin
    P := P + Length(SearchKey);
    P2 := Pos(':', Copy(Json, P, Length(Json) - P + 1));
    if P2 > 0 then
    begin
      P := P + P2;
      while (P <= Length(Json)) and ((Json[P] = ' ') or (Json[P] = #13) or (Json[P] = #10) or (Json[P] = #9)) do
        P := P + 1;
      PEnd := P;
      while (PEnd <= Length(Json)) and (Json[PEnd] <> ',') and (Json[PEnd] <> '}') and (Json[PEnd] <> #13) and (Json[PEnd] <> #10) do
        PEnd := PEnd + 1;
      ValStr := LowerCase(Trim(Copy(Json, P, PEnd - P)));
      if ValStr = 'false' then
        Result := False
      else if ValStr = 'true' then
        Result := True;
    end;
  end;
end;

function LoadExistingConfig(): Boolean;
var
  ConfigPath: String;
  PrevDir: String;
  JsonContent: AnsiString;
begin
  Result := False;
  ExistingLichessToken := '';
  ExistingLanguage := '';
  ExistingIsPublicSet := False;
  ExistingIsPublic := False;
  
  // 1. Check user app data location first (always safe and available during wizard init)
  ConfigPath := ExpandConstant('{userappdata}') + '\Opening Fenix\config.json';
  
  // 2. Check previous install path from registry
  if not FileExists(ConfigPath) then
  begin
    if RegQueryStringValue(HKLM64, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{{D37E84B1-29A4-4E67-8F12-78A3311E6F01}}_is1', 'Inno Setup: App Path', PrevDir) or
       RegQueryStringValue(HKCU64, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{{D37E84B1-29A4-4E67-8F12-78A3311E6F01}}_is1', 'Inno Setup: App Path', PrevDir) or
       RegQueryStringValue(HKLM32, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{{D37E84B1-29A4-4E67-8F12-78A3311E6F01}}_is1', 'Inno Setup: App Path', PrevDir) or
       RegQueryStringValue(HKCU32, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{{D37E84B1-29A4-4E67-8F12-78A3311E6F01}}_is1', 'Inno Setup: App Path', PrevDir) then
    begin
      ConfigPath := PrevDir + '\config.json';
    end;
  end;

  // 3. Check default installation directory
  if not FileExists(ConfigPath) then
  begin
    ConfigPath := ExpandConstant('{autopf}') + '\Opening Fenix\config.json';
  end;

  if FileExists(ConfigPath) then
  begin
    if LoadStringFromFile(ConfigPath, JsonContent) then
    begin
      Result := True;
      ExistingLichessToken := ExtractJsonValue(String(JsonContent), 'lichess_token');
      ExistingLanguage := ExtractJsonValue(String(JsonContent), 'ui_language');
      if Pos('"is_public"', String(JsonContent)) > 0 then
      begin
        ExistingIsPublicSet := True;
        ExistingIsPublic := ExtractJsonBool(String(JsonContent), 'is_public', False);
      end;
    end;
  end;
end;

procedure OpenLichessUrl(Sender: TObject);
var
  ErrorCode: Integer;
begin
  ShellExec('open', 'https://lichess.org/account/oauth/token', '', '', SW_SHOWNORMAL, ewNoWait, ErrorCode);
end;

procedure InitializeWizard;
var
  DescLabel: TNewStaticText;
  PromptLabel: TNewStaticText;
  SkipLabel: TNewStaticText;
begin
  IsUpgradeMode := LoadExistingConfig();

  { Create custom page after destination folder selection page }
  LichessPage := CreateCustomPage(wpSelectDir, ExpandConstant('{cm:LichessTitle}'), ExpandConstant('{cm:LichessSubTitle}'));

  DescLabel := TNewStaticText.Create(LichessPage);
  DescLabel.Parent := LichessPage.Surface;
  DescLabel.Caption := ExpandConstant('{cm:LichessDesc}');
  DescLabel.Left := 0;
  DescLabel.Top := 0;
  DescLabel.Width := LichessPage.SurfaceWidth;
  DescLabel.WordWrap := True;

  LichessLinkLabel := TNewStaticText.Create(LichessPage);
  LichessLinkLabel.Parent := LichessPage.Surface;
  LichessLinkLabel.Caption := ExpandConstant('{cm:LichessLinkText}');
  LichessLinkLabel.Left := 0;
  LichessLinkLabel.Top := DescLabel.Top + DescLabel.Height + 15;
  LichessLinkLabel.Font.Color := clBlue;
  LichessLinkLabel.Font.Style := [fsUnderline];
  LichessLinkLabel.Cursor := crHand;
  LichessLinkLabel.OnClick := @OpenLichessUrl;

  PromptLabel := TNewStaticText.Create(LichessPage);
  PromptLabel.Parent := LichessPage.Surface;
  PromptLabel.Caption := ExpandConstant('{cm:LichessPrompt}');
  PromptLabel.Left := 0;
  PromptLabel.Top := LichessLinkLabel.Top + 35;

  LichessEdit := TNewEdit.Create(LichessPage);
  LichessEdit.Parent := LichessPage.Surface;
  LichessEdit.Left := 0;
  LichessEdit.Top := PromptLabel.Top + 20;
  LichessEdit.Width := LichessPage.SurfaceWidth;
  if ExistingLichessToken <> '' then
  begin
    LichessEdit.Text := ExistingLichessToken;
  end;

  SkipLabel := TNewStaticText.Create(LichessPage);
  SkipLabel.Parent := LichessPage.Surface;
  SkipLabel.Caption := ExpandConstant('{cm:LichessSkipHint}');
  SkipLabel.Left := 0;
  SkipLabel.Top := LichessEdit.Top + 35;
  SkipLabel.Width := LichessPage.SurfaceWidth;
  SkipLabel.WordWrap := True;
  SkipLabel.Font.Style := [fsItalic];
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;
  // If upgrading and we already have an existing configuration, skip the Lichess token setup page
  if (PageID = LichessPage.ID) and IsUpgradeMode and (ExistingLichessToken <> '') then
  begin
    Result := True;
  end;
end;

function FindLastChar(const S: String; C: Char): Integer;
var
  I: Integer;
begin
  Result := 0;
  for I := Length(S) downto 1 do
  begin
    if S[I] = C then
    begin
      Result := I;
      Exit;
    end;
  end;
end;

function UpdateOrAddJsonKey(const Json, Key, NewValue: String; IsString: Boolean): String;
var
  P, P2, P3, PEnd: Integer;
  SearchKey: String;
  FormattedVal: String;
  NewPair: String;
begin
  Result := Json;
  if IsString then
    FormattedVal := '"' + NewValue + '"'
  else
    FormattedVal := NewValue;

  SearchKey := '"' + Key + '"';
  P := Pos(SearchKey, Result);
  if P > 0 then
  begin
    P2 := Pos(':', Copy(Result, P, Length(Result) - P + 1));
    if P2 > 0 then
    begin
      P2 := P + P2 - 1;
      P3 := P2 + 1;
      while (P3 <= Length(Result)) and ((Result[P3] = ' ') or (Result[P3] = #13) or (Result[P3] = #10) or (Result[P3] = #9)) do
        P3 := P3 + 1;
      
      PEnd := P3;
      if (PEnd <= Length(Result)) and (Result[PEnd] = '"') then
      begin
        PEnd := PEnd + 1;
        while (PEnd <= Length(Result)) and (Result[PEnd] <> '"') do
          PEnd := PEnd + 1;
        if PEnd <= Length(Result) then
          PEnd := PEnd + 1;
      end
      else
      begin
        while (PEnd <= Length(Result)) and (Result[PEnd] <> ',') and (Result[PEnd] <> #13) and (Result[PEnd] <> #10) and (Result[PEnd] <> '}') do
          PEnd := PEnd + 1;
      end;
      
      Result := Copy(Result, 1, P3 - 1) + FormattedVal + Copy(Result, PEnd, Length(Result) - PEnd + 1);
    end;
  end
  else
  begin
    PEnd := FindLastChar(Result, '}');
    if PEnd > 0 then
    begin
      NewPair := '    "' + Key + '": ' + FormattedVal;
      P2 := PEnd - 1;
      while (P2 > 0) and ((Result[P2] = ' ') or (Result[P2] = #13) or (Result[P2] = #10) or (Result[P2] = #9)) do
        P2 := P2 - 1;
      if (P2 > 0) and (Result[P2] <> '{') and (Result[P2] <> ',') then
      begin
        Result := Copy(Result, 1, P2) + ',' + Copy(Result, P2 + 1, PEnd - P2 - 1) + #13#10 + NewPair + #13#10 + '}' + Copy(Result, PEnd + 1, Length(Result) - PEnd);
      end
      else
      begin
        Result := Copy(Result, 1, PEnd - 1) + NewPair + #13#10 + '}' + Copy(Result, PEnd + 1, Length(Result) - PEnd);
      end;
    end;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ConfigPath: String;
  LichessKey: String;
  LangCode: String;
  EnginePath: String;
  JsonContentStr: String;
  JsonContentAnsi: AnsiString;
  EscapedEnginePath: String;
  IsPublicStr: String;
  TargetPaths: array[0..1] of String;
  I: Integer;
begin
  if CurStep = ssPostInstall then
  begin
    LichessKey := Trim(LichessEdit.Text);
    if (LichessKey = '') and (ExistingLichessToken <> '') then
      LichessKey := ExistingLichessToken;

    LangCode := ExpandConstant('{language}');
    if LangCode <> 'de' then
      LangCode := 'en';

    #if AppBuildType == "Public"
    if IsUpgradeMode and ExistingIsPublicSet and (not ExistingIsPublic) then
    begin
      // Preserve existing PRIVATE mode even when updating via public package
      IsPublicStr := 'false';
    end
    else
    begin
      IsPublicStr := 'true';
    end;
    #else
    IsPublicStr := 'false';
    #endif

    if IsPublicStr = 'false' then
    begin
      if FileExists(ExpandConstant('{app}') + '\PUBLIC_VERSION') then
        DeleteFile(ExpandConstant('{app}') + '\PUBLIC_VERSION');
    end;

    EnginePath := ExpandConstant('{app}') + '\engines\stockfish-windows-x86-64-avx2.exe';
    EscapedEnginePath := EnginePath;
    StringChangeEx(EscapedEnginePath, '\', '\\', True);

    TargetPaths[0] := ExpandConstant('{app}') + '\config.json';
    TargetPaths[1] := ExpandConstant('{userappdata}') + '\Opening Fenix\config.json';

    for I := 0 to 1 do
    begin
      ConfigPath := TargetPaths[I];
      if FileExists(ConfigPath) then
      begin
        if LoadStringFromFile(ConfigPath, JsonContentAnsi) then
        begin
          JsonContentStr := String(JsonContentAnsi);
          JsonContentStr := UpdateOrAddJsonKey(JsonContentStr, 'engine_path', EscapedEnginePath, True);
          if LichessKey <> '' then
            JsonContentStr := UpdateOrAddJsonKey(JsonContentStr, 'lichess_token', LichessKey, True);
          JsonContentStr := UpdateOrAddJsonKey(JsonContentStr, 'ui_language', LangCode, True);
          JsonContentStr := UpdateOrAddJsonKey(JsonContentStr, 'is_public', IsPublicStr, False);
          SaveStringToFile(ConfigPath, AnsiString(JsonContentStr), False);
        end;
      end
      else if I = 0 then
      begin
        JsonContentStr := '{' + #13#10 +
          '    "engine_path": "' + EscapedEnginePath + '",' + #13#10 +
          '    "lichess_token": "' + LichessKey + '",' + #13#10 +
          '    "ui_language": "' + LangCode + '",' + #13#10 +
          '    "is_public": ' + IsPublicStr + ',' + #13#10 +
          '    "master_volume": 30,' + #13#10 +
          '    "engine_threads": "4",' + #13#10 +
          '    "engine_hash": "256",' + #13#10 +
          '    "engine_depth": "20",' + #13#10 +
          '    "engine_multipv": "3"' + #13#10 +
          '}';
        SaveStringToFile(ConfigPath, AnsiString(JsonContentStr), False);
      end;
    end;
  end;
end;

